# Generated by Django 2.2.15 on 2020-09-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0005_auto_20200916_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='note_replied_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.Note'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_responses', to='main.Note'),
        ),
        migrations.AlterField(
            model_name='gitlabfile',
            name='tag',
            field=models.CharField(choices=[('code', 'code'), ('data', 'data'), ('documentation', 'documentation')], max_length=14),
        ),
        migrations.AlterField(
            model_name='note',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Manuscript'),
        ),
    ]
