# Generated by Django 2.2.10 on 2020-02-17 21:40

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_init', 'Awaiting Initial Submission'), ('awaiting_resub', 'Awaiting Resubmission'), ('processing', 'Processing Submission'), ('completed', 'Completed')], default='new', max_length=15),
        ),
    ]
