# Generated by Django 2.2 on 2020-01-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_curator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='author_manuscripts',
            field=models.ManyToManyField(related_name='author_manuscripts', to='main.Manuscript'),
        ),
        migrations.AddField(
            model_name='user',
            name='curator_manuscripts',
            field=models.ManyToManyField(related_name='curator_manuscripts', to='main.Manuscript'),
        ),
        migrations.AddField(
            model_name='user',
            name='editor_manuscripts',
            field=models.ManyToManyField(related_name='editor_manuscripts', to='main.Manuscript'),
        ),
        migrations.AddField(
            model_name='user',
            name='verifier_manuscripts',
            field=models.ManyToManyField(related_name='verifier_manuscripts', to='main.Manuscript'),
        ),
    ]
