# Generated by Django 3.1.6 on 2021-02-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnote',
            name='parent_file',
        ),
        migrations.RemoveField(
            model_name='note',
            name='parent_file',
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='ref_file',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.gitfile'),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='ref_file_type',
            field=models.CharField(choices=[('-', '-'), ('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other')], default='-', max_length=14, verbose_name='file type'),
        ),
        migrations.AddField(
            model_name='note',
            name='ref_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_notes', to='main.gitfile'),
        ),
        migrations.AddField(
            model_name='note',
            name='ref_file_type',
            field=models.CharField(choices=[('-', '-'), ('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other')], default='-', max_length=14, verbose_name='file type'),
        ),
    ]
