# Generated by Django 3.1.8 on 2021-04-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='files_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='files_changed',
            field=models.BooleanField(default=True),
        ),
    ]
