# Generated by Django 2.2.15 on 2020-09-14 18:43

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0004_gitlabfile_gitlab_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscript',
            options={'permissions': [('add_authors_on_manuscript', 'Can manage authors on manuscript'), ('remove_authors_on_manuscript', 'Can manage authors on manuscript'), ('manage_editors_on_manuscript', 'Can manage editors on manuscript'), ('manage_curators_on_manuscript', 'Can manage curators on manuscript'), ('manage_verifiers_on_manuscript', 'Can manage verifiers on manuscript'), ('add_submission_to_manuscript', 'Can add submission to manuscript'), ('approve_manuscript_submissions', 'Can approve submissions for review'), ('curate_manuscript', 'Can curate manuscript/submission'), ('verify_manuscript', 'Can verify manuscript/submission')]},
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress_editing', 'In Progress - Editing'), ('in_progress_curation', 'In Progress - Curation'), ('in_progress_verification', 'In Progress - Verification'), ('reviewed_awaiting_report', 'Reviewed - Awaiting Report'), ('reviewed_awaiting_approval', 'Reviewed - Report Awaiting Approval'), ('returned', 'Returned')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='submission',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress_editing', 'In Progress - Editing'), ('in_progress_curation', 'In Progress - Curation'), ('in_progress_verification', 'In Progress - Verification'), ('reviewed_awaiting_report', 'Reviewed - Awaiting Report'), ('reviewed_awaiting_approval', 'Reviewed - Report Awaiting Approval'), ('returned', 'Returned')], default='new', max_length=25),
        ),
    ]
