# Generated by Django 2.2.10 on 2020-02-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200217_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='note_text',
        ),
    ]
