# Generated by Django 2.2.15 on 2020-11-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_datasource_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_data_sources', to='main.Manuscript'),
        ),
    ]
