# Generated by Django 3.1.6 on 2021-02-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210219_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='ref_cycle',
            field=models.CharField(choices=[('submission', 'Submission'), ('edition', 'Edition'), ('curation', 'Curation'), ('verification', 'Verification')], default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='ref_cycle',
            field=models.CharField(choices=[('submission', 'Submission'), ('edition', 'Edition'), ('curation', 'Curation'), ('verification', 'Verification')], default='blah', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gitfile',
            name='tag',
            field=models.CharField(choices=[('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other'), ('-', '-')], default='-', max_length=14, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='ref_file_type',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other'), ('-', '-')], max_length=14, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='note',
            name='ref_file_type',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other'), ('-', '-')], max_length=14, verbose_name='file type'),
        ),
    ]
