# Generated by Django 3.2.12 on 2022-02-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220214_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationmetadata',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='verificationmetadata',
            name='last_editor',
        ),
        migrations.RemoveField(
            model_name='verificationmetadata',
            name='manuscript',
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='host_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Hosting Institution URL'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='machine_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Machine Type'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='memory_reqs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Memory Reqirements'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='operating_system',
            field=models.CharField(default='', max_length=200, verbose_name='Operating System'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='packages_info',
            field=models.TextField(default='', help_text='Please provide the list of your required packages and their versions.', verbose_name='Required Packages'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='processor_reqs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Processor Requirements'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='scheduler',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Scheduler Module'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='software_info',
            field=models.TextField(default='', help_text='Please provide the list of your used statistical software and their versions.', verbose_name='Statistical Software'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='host_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Hosting Institution URL'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='machine_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Machine Type'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='memory_reqs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Memory Reqirements'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='operating_system',
            field=models.CharField(default='', max_length=200, verbose_name='Operating System'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='packages_info',
            field=models.TextField(default='', help_text='Please provide the list of your required packages and their versions.', verbose_name='Required Packages'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='processor_reqs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Processor Requirements'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='scheduler',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Scheduler Module'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='software_info',
            field=models.TextField(default='', help_text='Please provide the list of your used statistical software and their versions.', verbose_name='Statistical Software'),
        ),
        migrations.DeleteModel(
            name='HistoricalVerificationMetadata',
        ),
        migrations.DeleteModel(
            name='VerificationMetadata',
        ),
    ]
