# Generated by Django 2.2 on 2020-01-27 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200123_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author_submissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='curator_curations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='editor_manuscripts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verifier_verifications',
        ),
        migrations.AddField(
            model_name='curation',
            name='curators',
            field=models.ManyToManyField(blank=True, related_name='curator_curations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editor_manuscripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='author_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verification',
            name='verifiers',
            field=models.ManyToManyField(blank=True, related_name='verifier_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
