# Generated by Django 3.2.11 on 2022-01-17 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211130_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corereinvitation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='corereinvitation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='invite_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invite_key',
        ),
        migrations.AddField(
            model_name='corereinvitation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to=settings.AUTH_USER_MODEL),
        ),
    ]
