# Generated by Django 3.2.5 on 2021-12-14 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211214_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.corereinvitation'),
        ),
    ]
