# Generated by Django 2.2.15 on 2020-11-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201110_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='contents_gis',
            field=models.BooleanField(default=False, verbose_name='Does this submission contain GIS data and mapping?'),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='contents_proprietary',
            field=models.BooleanField(default=False, verbose_name='Does this submission contain restricted or proprietary data?'),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='contents_proprietary_sharing',
            field=models.BooleanField(default=False, verbose_name='If yes, are you permitted to share these data with Odum for verification only?'),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='high_performance',
            field=models.BooleanField(default=False, verbose_name='Does this submission require a high-performance compute environment?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='contents_gis',
            field=models.BooleanField(default=False, verbose_name='Does this submission contain GIS data and mapping?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='contents_proprietary',
            field=models.BooleanField(default=False, verbose_name='Does this submission contain restricted or proprietary data?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='contents_proprietary_sharing',
            field=models.BooleanField(default=False, verbose_name='If yes, are you permitted to share these data with Odum for verification only?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='high_performance',
            field=models.BooleanField(default=False, verbose_name='Does this submission require a high-performance compute environment?'),
        ),
    ]
