# Generated by Django 2.2.15 on 2020-09-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200914_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='parent_edition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.Edition'),
        ),
        migrations.AddField(
            model_name='note',
            name='parent_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.Edition'),
        ),
    ]
