# Generated by Django 2.2.10 on 2020-02-19 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_manuscript_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='curation',
            name='submission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission_curation', to='main.Submission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='submission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission_verification', to='main.Submission'),
            preserve_default=False,
        ),
    ]
