# Generated by Django 3.2.12 on 2022-02-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220216_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanuscript',
            name='other_exemptions',
            field=models.TextField(blank=True, default='', help_text='Are there any other exemptions to the verification workflow that the curation team should know about?', max_length=1024, null=True, verbose_name='Other Exemptions'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='other_exemptions',
            field=models.TextField(blank=True, default='', help_text='Are there any other exemptions to the verification workflow that the curation team should know about?', max_length=1024, null=True, verbose_name='Other Exemptions'),
        ),
    ]
