# Generated by Django 3.2.11 on 2022-01-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220117_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanuscript',
            name='internal_mode',
            field=models.BooleanField(default=False, help_text='Is this manuscript being run without external Authors or Editors'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='internal_mode',
            field=models.BooleanField(default=False, help_text='Is this manuscript being run without external Authors or Editors'),
        ),
    ]
