# Generated by Django 2.2.15 on 2020-08-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200826_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabfile',
            name='gitlab_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
