# Generated by Django 3.1.6 on 2021-02-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210222_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='report',
            field=models.TextField(default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='report',
            field=models.TextField(default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='gitfile',
            name='tag',
            field=models.CharField(choices=[('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other')], max_length=14, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='historicalcuration',
            name='report',
            field=models.TextField(default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='historicaledition',
            name='report',
            field=models.TextField(default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='ref_file_type',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other')], max_length=14, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='historicalverification',
            name='report',
            field=models.TextField(default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='note',
            name='ref_file_type',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other')], max_length=14, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='report',
            field=models.TextField(default='', verbose_name='Report'),
        ),
    ]
