# Generated by Django 2.2 on 2020-01-30 23:48

import corere.main.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200127_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='manuscript_file',
            field=models.FileField(blank=True, upload_to=corere.main.models.manuscript_directory_path),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
