# Generated by Django 2.2.15 on 2020-11-11 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201110_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date model was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date model was last updated', verbose_name='updated at')),
                ('operating_system', models.CharField(default='', max_length=200, verbose_name='operating system')),
                ('machine_type', models.CharField(default='', max_length=200, verbose_name='machine type')),
                ('software_name', models.CharField(default='', max_length=200, verbose_name='software name')),
                ('software_version', models.CharField(default='', max_length=200, verbose_name='software version')),
                ('code_repo_url', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='code repository url')),
                ('scheduler', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='scheduler module')),
                ('platform', models.CharField(default='', max_length=200, verbose_name='platform')),
                ('processor_reqs', models.CharField(default='', max_length=200, verbose_name='processor requirements')),
                ('host_url', models.CharField(default='', max_length=200, verbose_name='hosting institution url')),
                ('memory_reqs', models.CharField(default='', max_length=200, verbose_name='memory reqirements')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_verificationmetadatas', to=settings.AUTH_USER_MODEL, verbose_name='Creator User')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor_verificationmetadatas', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='curation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_curations', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='curation',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor_curations', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_editions', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor_editions', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='gitlabfile',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_gitlabfiles', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='gitlabfile',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor_gitlabfiles', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='historicalcuration',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='historicalcuration',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='historicaledition',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='historicaledition',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='historicalverification',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='historicalverification',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_manuscripts', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor_manuscripts', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_notes', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor_notes', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User'),
        ),
        migrations.CreateModel(
            name='VerificationMetadataPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('version', models.CharField(default='', max_length=200, verbose_name='version')),
                ('source_default_repo', models.BooleanField(default=False, verbose_name='default repository')),
                ('source_cran', models.BooleanField(default=False, verbose_name='CRAN')),
                ('source_author_website', models.BooleanField(default=False, verbose_name='author website')),
                ('source_dataverse', models.BooleanField(default=False, verbose_name='dataverse archive')),
                ('source_other', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='other')),
                ('verification_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificationmetadata_packages', to='main.VerificationMetadata')),
            ],
        ),
        migrations.AddField(
            model_name='verificationmetadata',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_vmetadata', to='main.Submission'),
        ),
    ]
