# Generated by Django 2.2 on 2020-01-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200130_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
