# Generated by Django 3.1.6 on 2021-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210223_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnote',
            name='parent_curation',
        ),
        migrations.RemoveField(
            model_name='historicalnote',
            name='parent_edition',
        ),
        migrations.RemoveField(
            model_name='historicalnote',
            name='parent_verification',
        ),
        migrations.RemoveField(
            model_name='note',
            name='parent_curation',
        ),
        migrations.RemoveField(
            model_name='note',
            name='parent_edition',
        ),
        migrations.RemoveField(
            model_name='note',
            name='parent_verification',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
