# Generated by Django 3.2.11 on 2022-01-19 20:06

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220118_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('incom_materials', 'Incomplete Materials'), ('major_issues', 'Major Issues'), ('minor_issues', 'Minor Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the curator', max_length=15, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('issues', 'Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the editor', max_length=15, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='historicalcuration',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('incom_materials', 'Incomplete Materials'), ('major_issues', 'Major Issues'), ('minor_issues', 'Minor Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the curator', max_length=15, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='historicaledition',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('issues', 'Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the editor', max_length=15, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='historicalverification',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('not_attempted', 'Not Attempted'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('success_w_mod', 'Success with Modification'), ('success', 'Success')], default='new', help_text='Was the submission able to be verified', max_length=15, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('not_attempted', 'Not Attempted'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('success_w_mod', 'Success with Modification'), ('success', 'Success')], default='new', help_text='Was the submission able to be verified', max_length=15, verbose_name='Review'),
        ),
    ]
