# Generated by Django 2.2.15 on 2020-09-16 20:45

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200915_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress_edition', 'In Progress - Edition'), ('in_progress_curation', 'In Progress - Curation'), ('in_progress_verification', 'In Progress - Verification'), ('reviewed_awaiting_report', 'Reviewed - Awaiting Report'), ('reviewed_awaiting_approve', 'Reviewed - Report Awaiting Approval'), ('returned', 'Returned')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='submission',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress_edition', 'In Progress - Edition'), ('in_progress_curation', 'In Progress - Curation'), ('in_progress_verification', 'In Progress - Verification'), ('reviewed_awaiting_report', 'Reviewed - Awaiting Report'), ('reviewed_awaiting_approve', 'Reviewed - Report Awaiting Approval'), ('returned', 'Returned')], default='new', max_length=25),
        ),
    ]
