# Generated by Django 2.2.10 on 2020-02-19 22:31

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200219_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='environment_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
            preserve_default=False,
        ),
    ]
