# Generated by Django 3.2.5 on 2021-12-14 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corereinvitation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='corereinvitation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invite',
        ),
        migrations.AddField(
            model_name='corereinvitation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to=settings.AUTH_USER_MODEL),
        ),
    ]
