# Generated by Django 3.2.1 on 2021-05-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_containerinfo_build_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerinfo',
            name='submission_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
