# Generated by Django 2.2.10 on 2020-02-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_manuscript_environment_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscript',
            options={'permissions': [('manage_authors_on_manuscript', 'Can manage authors on manuscript'), ('manage_editors_on_manuscript', 'Can manage editors on manuscript'), ('manage_curators_on_manuscript', 'Can manage curators on manuscript'), ('manage_verifiers_on_manuscript', 'Can manage verifiers on manuscript')]},
        ),
    ]
