# Generated by Django 3.2.12 on 2022-02-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220218_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmanuscript',
            old_name='contents_proprietary',
            new_name='contents_restricted',
        ),
        migrations.RenameField(
            model_name='historicalmanuscript',
            old_name='contents_proprietary_sharing',
            new_name='contents_restricted_sharing',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='contents_proprietary',
            new_name='contents_restricted',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='contents_proprietary_sharing',
            new_name='contents_restricted_sharing',
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='qdr_review',
            field=models.BooleanField(default=False, verbose_name='Does this manuscript need verification of qualitative results by QDR?'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='qual_analysis',
            field=models.BooleanField(default=False, verbose_name='Does this manuscript include qualitative analysis'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='qdr_review',
            field=models.BooleanField(default=False, verbose_name='Does this manuscript need verification of qualitative results by QDR?'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='qual_analysis',
            field=models.BooleanField(default=False, verbose_name='Does this manuscript include qualitative analysis'),
        ),
    ]
