# Generated by Django 2.2.15 on 2020-11-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201111_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationmetadata',
            name='code_repo_url',
        ),
        migrations.RemoveField(
            model_name='verificationmetadata',
            name='software_name',
        ),
        migrations.RemoveField(
            model_name='verificationmetadata',
            name='software_version',
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='host_url',
            field=models.URLField(default='', verbose_name='hosting institution url'),
        ),
        migrations.CreateModel(
            name='VerificationMetadataSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('version', models.CharField(default='', max_length=200, verbose_name='version')),
                ('code_repo_url', models.URLField(blank=True, default='', null=True, verbose_name='code repository url')),
                ('verification_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificationmetadata_softwares', to='main.VerificationMetadata')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationMetadataBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('type', models.CharField(default='', max_length=200, verbose_name='type')),
                ('version', models.CharField(default='', max_length=200, verbose_name='version')),
                ('definition_url', models.URLField(default='', verbose_name='definition url')),
                ('logo_url', models.URLField(default='', verbose_name='logo url')),
                ('issuing_org', models.CharField(default='', max_length=200, verbose_name='issuing organization')),
                ('issuing_date', models.DateField(verbose_name='issuing date')),
                ('verification_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificationmetadata_badges', to='main.VerificationMetadata')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationMetadataAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('version', models.CharField(default='', max_length=200, verbose_name='version')),
                ('url', models.URLField(default='', verbose_name='url')),
                ('organization', models.CharField(default='', max_length=200, verbose_name='organization')),
                ('verified_results', models.CharField(default='', max_length=200, verbose_name='verified results')),
                ('code_executability', models.CharField(default='', max_length=200, verbose_name='code executability')),
                ('exceptions', models.CharField(default='', max_length=200, verbose_name='exceptions')),
                ('exception_reason', models.CharField(default='', max_length=200, verbose_name='exception reason')),
                ('verification_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificationmetadata_audits', to='main.VerificationMetadata')),
            ],
        ),
    ]
