# Generated by Django 3.2.11 on 2022-01-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220119_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmanuscript',
            old_name='internal_mode',
            new_name='skip_edition',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='internal_mode',
            new_name='skip_edition',
        ),
    ]
