# Generated by Django 2.2.15 on 2020-11-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201112_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationmetadataaudit',
            name='code_executability',
        ),
        migrations.AddField(
            model_name='curation',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='report'),
        ),
        migrations.AddField(
            model_name='edition',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='report'),
        ),
        migrations.AddField(
            model_name='historicalcuration',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='report'),
        ),
        migrations.AddField(
            model_name='historicaledition',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='report'),
        ),
        migrations.AddField(
            model_name='historicalverification',
            name='code_executability',
            field=models.CharField(default='', max_length=2000, verbose_name='code executability'),
        ),
        migrations.AddField(
            model_name='historicalverification',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='report'),
        ),
        migrations.AddField(
            model_name='verification',
            name='code_executability',
            field=models.CharField(default='', max_length=2000, verbose_name='code executability'),
        ),
        migrations.AddField(
            model_name='verification',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='qdr_review',
            field=models.BooleanField(default=False, help_text='Was this manuscript reviewed by the Qualitative Data Repository?', verbose_name='QDR Review'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='qdr_review',
            field=models.BooleanField(default=False, help_text='Was this manuscript reviewed by the Qualitative Data Repository?', verbose_name='QDR Review'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_vmetadata', to='main.Submission'),
        ),
    ]
