# Generated by Django 3.2.12 on 2022-02-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220222_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanuscript',
            name='exemption_override',
            field=models.BooleanField(default=False, help_text='The curation team has decided to deploy this manuscript inside Whole Tale, even with potential issues.', verbose_name='Exemption Override'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='exemption_override',
            field=models.BooleanField(default=False, help_text='The curation team has decided to deploy this manuscript inside Whole Tale, even with potential issues.', verbose_name='Exemption Override'),
        ),
    ]
