# Generated by Django 3.2.1 on 2021-05-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_containerinfo_proxy_container_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerinfo',
            old_name='proxy_container_ip',
            new_name='proxy_container_address',
        ),
    ]
