# Generated by Django 3.1.7 on 2021-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210309_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationmetadata',
            name='packages_info',
            field=models.TextField(default='', help_text='Please provide the list of your packages and their versions.', verbose_name='Packages Info'),
        ),
        migrations.DeleteModel(
            name='VerificationMetadataPackage',
        ),
    ]
