# Generated by Django 2.2.10 on 2020-02-24 22:48

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200220_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('submitted', 'Submitted')], default='new', max_length=15),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='environment_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
