# Generated by Django 3.2.11 on 2022-01-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220124_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanuscript',
            name='wt_compute_env_other',
            field=models.TextField(blank=True, default='', help_text='Please provide us details about your unlisted environment', max_length=1024, null=True, verbose_name='Other Environment Details'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='wt_compute_env_other',
            field=models.TextField(blank=True, default='', help_text='Please provide us details about your unlisted environment', max_length=1024, null=True, verbose_name='Other Environment Details'),
        ),
    ]
