# Generated by Django 2.2.9 on 2020-02-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200203_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='editors',
        ),
    ]
