# Generated by Django 2.2.15 on 2020-11-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201130_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationmetadatabadge',
            name='type',
        ),
        migrations.AddField(
            model_name='verificationmetadatabadge',
            name='badge_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email address of the publication contact that will be stored in Dataverse', max_length=254, null=True, verbose_name='contact email address'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Additional info about the manuscript', max_length=1024, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='producer_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='producer first name'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='producer_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='producer last name'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='qdr_review',
            field=models.BooleanField(blank=True, default=False, help_text='Was this manuscript reviewed by the Qualitative Data Repository?', null=True, verbose_name='QDR Review'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='qual_analysis',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this manuscript needs qualitative analysis', null=True, verbose_name='qualitative analysis'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='subject',
            field=models.CharField(blank=True, choices=[('agricultural', 'Agricultural Sciences'), ('arts', 'Arts and Humanities'), ('astronomy', 'Astronomy and Astrophysics'), ('business', 'Business and Management'), ('chemistry', 'Chemistry'), ('computer', 'Computer and Information Science'), ('environmental', 'Earth and Environmental Sciences'), ('engineering', 'Engineering'), ('law', 'Law'), ('mathematics', 'Mathematical Sciences'), ('health', 'Medicine, Health and Life Sciences'), ('physics', 'Physics'), ('social', 'Social Sciences'), ('other', 'Other')], max_length=14, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title of the manuscript', max_length=200, null=True, verbose_name='manuscript title'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='contents_gis',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Does this submission contain GIS data and mapping?'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='contents_proprietary',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Does this submission contain restricted or proprietary data?'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='contents_proprietary_sharing',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='If yes, are you permitted to share these data with Odum for verification only?'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='high_performance',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Does this submission require a high-performance compute environment?'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email address of the publication contact that will be stored in Dataverse', max_length=254, null=True, verbose_name='contact email address'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Additional info about the manuscript', max_length=1024, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='producer_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='producer first name'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='producer_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='producer last name'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='qdr_review',
            field=models.BooleanField(blank=True, default=False, help_text='Was this manuscript reviewed by the Qualitative Data Repository?', null=True, verbose_name='QDR Review'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='qual_analysis',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this manuscript needs qualitative analysis', null=True, verbose_name='qualitative analysis'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='subject',
            field=models.CharField(blank=True, choices=[('agricultural', 'Agricultural Sciences'), ('arts', 'Arts and Humanities'), ('astronomy', 'Astronomy and Astrophysics'), ('business', 'Business and Management'), ('chemistry', 'Chemistry'), ('computer', 'Computer and Information Science'), ('environmental', 'Earth and Environmental Sciences'), ('engineering', 'Engineering'), ('law', 'Law'), ('mathematics', 'Mathematical Sciences'), ('health', 'Medicine, Health and Life Sciences'), ('physics', 'Physics'), ('social', 'Social Sciences'), ('other', 'Other')], max_length=14, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title of the manuscript', max_length=200, null=True, verbose_name='manuscript title'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contents_gis',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Does this submission contain GIS data and mapping?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contents_proprietary',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Does this submission contain restricted or proprietary data?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contents_proprietary_sharing',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='If yes, are you permitted to share these data with Odum for verification only?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='high_performance',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Does this submission require a high-performance compute environment?'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='host_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='hosting institution url'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='machine_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='machine type'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='memory_reqs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='memory reqirements'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='operating_system',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='operating system'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='processor_reqs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='processor requirements'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='exception_reason',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='exception reason'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='exceptions',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='exceptions'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='verified_results',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='verified results'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='version',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='definition_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='definition url'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='issuing_date',
            field=models.DateField(blank=True, null=True, verbose_name='issuing date'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='issuing_org',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='issuing organization'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='logo_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='logo url'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='version',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='source_author_website',
            field=models.BooleanField(blank=True, default=False, verbose_name='author website'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='source_cran',
            field=models.BooleanField(blank=True, default=False, verbose_name='CRAN'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='source_dataverse',
            field=models.BooleanField(blank=True, default=False, verbose_name='dataverse archive'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='source_default_repo',
            field=models.BooleanField(blank=True, default=False, verbose_name='default repository'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='version',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatasoftware',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatasoftware',
            name='version',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='version'),
        ),
    ]
