# Generated by Django 2.2.10 on 2020-02-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200224_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_curations', to='main.Manuscript'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_submissions', to='main.Manuscript'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_verifications', to='main.Manuscript'),
        ),
    ]
