# Generated by Django 3.1.7 on 2021-03-10 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210309_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVerificationMetadataSoftware',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_change_list', models.TextField(default='')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Name')),
                ('version', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Version')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verification_metadata', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.verificationmetadata')),
            ],
            options={
                'verbose_name': 'historical verification metadata software',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVerificationMetadataBadge',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_change_list', models.TextField(default='')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Name')),
                ('badge_type', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Type')),
                ('version', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Version')),
                ('definition_url', models.URLField(blank=True, default='', null=True, verbose_name='Definition URL')),
                ('logo_url', models.URLField(blank=True, default='', null=True, verbose_name='Logo URL')),
                ('issuing_org', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Issuing Organization')),
                ('issuing_date', models.DateField(blank=True, null=True, verbose_name='Issuing Date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verification_metadata', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.verificationmetadata')),
            ],
            options={
                'verbose_name': 'historical verification metadata badge',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVerificationMetadataAudit',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_change_list', models.TextField(default='')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Name')),
                ('version', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Version')),
                ('url', models.URLField(blank=True, default='', null=True, verbose_name='URL')),
                ('organization', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Organization')),
                ('verified_results', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Verified Results')),
                ('exceptions', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Exceptions')),
                ('exception_reason', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Exception Reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verification_metadata', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.verificationmetadata')),
            ],
            options={
                'verbose_name': 'historical verification metadata audit',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVerificationMetadata',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Date model was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Date model was last updated', verbose_name='updated at')),
                ('history_change_list', models.TextField(default='')),
                ('operating_system', models.CharField(default='', max_length=200, verbose_name='Operating System')),
                ('machine_type', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Machine Type')),
                ('scheduler', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Scheduler Module')),
                ('platform', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Platform')),
                ('processor_reqs', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Processor Requirements')),
                ('host_url', models.URLField(blank=True, default='', null=True, verbose_name='Hosting Institution URL')),
                ('memory_reqs', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Memory Reqirements')),
                ('packages_info', models.TextField(default='', help_text='Please provide the list of your packages and their versions.', verbose_name='Packages Info')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator User')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User')),
                ('submission', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.submission')),
            ],
            options={
                'verbose_name': 'historical verification metadata',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
