# Generated by Django 3.2.12 on 2022-03-11 17:47

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220304_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('incomplete_materials', 'Incomplete Materials'), ('major_issues', 'Major Issues'), ('minor_issues', 'Minor Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the curator', max_length=32, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='gitfile',
            name='tag',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('data', 'Data'), ('documentation_readme', 'Documentation - Readme'), ('documentation_codebook', 'Documentation - Codebook'), ('documentation_other', 'Documentation - Other')], max_length=32, null=True, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='historicalcuration',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('incomplete_materials', 'Incomplete Materials'), ('major_issues', 'Major Issues'), ('minor_issues', 'Minor Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the curator', max_length=32, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('completed', 'Completed')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='ref_cycle',
            field=models.CharField(choices=[('submission', 'Submission'), ('edition', 'Edition'), ('curation', 'Curation'), ('verification', 'Verification')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='ref_file_type',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('data', 'Data'), ('documentation_readme', 'Documentation - Readme'), ('documentation_codebook', 'Documentation - Codebook'), ('documentation_other', 'Documentation - Other')], max_length=32, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress_edition', 'In Progress Edition'), ('rejected_editor', 'Rejected Editor'), ('in_progress_curation', 'In Progress Curation'), ('in_progress_verification', 'In Progress Verification'), ('reviewed_awaiting_report', 'Reviewed Awaiting Report'), ('reviewed_awaiting_approval', 'Reviewed Report Awaiting Approval'), ('returned', 'Returned')], default='new', help_text='The status of the submission in the review process', max_length=32, verbose_name='Submission review status'),
        ),
        migrations.AlterField(
            model_name='historicalverification',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('not_attempted', 'Not Attempted'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('success_with_modification', 'Success with Modification'), ('success', 'Success')], default='new', help_text='Was the submission able to be verified', max_length=32, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('completed', 'Completed')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
        migrations.AlterField(
            model_name='note',
            name='ref_cycle',
            field=models.CharField(choices=[('submission', 'Submission'), ('edition', 'Edition'), ('curation', 'Curation'), ('verification', 'Verification')], max_length=32),
        ),
        migrations.AlterField(
            model_name='note',
            name='ref_file_type',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('data', 'Data'), ('documentation_readme', 'Documentation - Readme'), ('documentation_codebook', 'Documentation - Codebook'), ('documentation_other', 'Documentation - Other')], max_length=32, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress_edition', 'In Progress Edition'), ('rejected_editor', 'Rejected Editor'), ('in_progress_curation', 'In Progress Curation'), ('in_progress_verification', 'In Progress Verification'), ('reviewed_awaiting_report', 'Reviewed Awaiting Report'), ('reviewed_awaiting_approval', 'Reviewed Report Awaiting Approval'), ('returned', 'Returned')], default='new', help_text='The status of the submission in the review process', max_length=32, verbose_name='Submission review status'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', '---'), ('not_attempted', 'Not Attempted'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('success_with_modification', 'Success with Modification'), ('success', 'Success')], default='new', help_text='Was the submission able to be verified', max_length=32, verbose_name='Review'),
        ),
    ]
