# Generated by Django 2.2.10 on 2020-02-26 20:58

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200225_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscript',
            options={'permissions': [('manage_authors_on_manuscript', 'Can manage authors on manuscript'), ('manage_editors_on_manuscript', 'Can manage editors on manuscript'), ('manage_curators_on_manuscript', 'Can manage curators on manuscript'), ('manage_verifiers_on_manuscript', 'Can manage verifiers on manuscript'), ('add_submission_to_manuscript', 'Can add submission to manuscript')]},
        ),
        migrations.RemoveField(
            model_name='curation',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='manuscript',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('reviewed', 'Reviewed')], default='new', max_length=15),
        ),
    ]
