# Generated by Django 3.2.11 on 2022-01-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220125_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='launch_issues',
            field=models.TextField(blank=True, default='', help_text='Issues noted by the author when attempting to launch the container', max_length=1024, null=True, verbose_name='Container Launch Issues'),
        ),
        migrations.AddField(
            model_name='submission',
            name='launch_issues',
            field=models.TextField(blank=True, default='', help_text='Issues noted by the author when attempting to launch the container', max_length=1024, null=True, verbose_name='Container Launch Issues'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='compute_env_other',
            field=models.TextField(blank=True, default='', help_text='Details about the unlisted environment', max_length=1024, null=True, verbose_name='Other Environment Details'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='compute_env_other',
            field=models.TextField(blank=True, default='', help_text='Details about the unlisted environment', max_length=1024, null=True, verbose_name='Other Environment Details'),
        ),
    ]
