# Generated by Django 2.2.15 on 2020-12-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201130_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='pub_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The internal ID from the publication', max_length=200, null=True, verbose_name='Publication ID'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='pub_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The internal ID from the publication', max_length=200, null=True, verbose_name='Publication ID'),
        ),
    ]
