# Generated by Django 2.2.9 on 2020-02-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200206_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscript',
            options={'permissions': [('manage_authors_on_manuscript', 'Can manage authors on manuscript')]},
        ),
    ]
