# Generated by Django 3.2.2 on 2021-07-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210616_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnote',
            name='text',
            field=models.TextField(verbose_name='Note Text'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(verbose_name='Note Text'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatasoftware',
            name='verification_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificationmetadata_softwares', to='main.verificationmetadata'),
        ),
    ]
