# Generated by Django 3.2.12 on 2022-02-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220131_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='launch_issues',
            field=models.TextField(blank=True, default='', help_text='Issues faced when attempting to launch the container', max_length=1024, null=True, verbose_name='Container Launch Issues'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='launch_issues',
            field=models.TextField(blank=True, default='', help_text='Issues faced when attempting to launch the container', max_length=1024, null=True, verbose_name='Container Launch Issues'),
        ),
    ]
