# Generated by Django 2.2.15 on 2020-12-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201201_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='title',
            field=models.CharField(default='', help_text='Title of the manuscript', max_length=200, verbose_name='manuscript title'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='contents_gis',
            field=models.BooleanField(default=False, verbose_name='Does this submission contain GIS data and mapping?'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='contents_proprietary',
            field=models.BooleanField(default=False, verbose_name='Does this submission contain restricted or proprietary data?'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='contents_proprietary_sharing',
            field=models.BooleanField(default=False, verbose_name='Are you restricted from sharing this data with Odum for verification only?'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='high_performance',
            field=models.BooleanField(default=False, verbose_name='Does this submission require a high-performance compute environment?'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.CharField(default='', help_text='Title of the manuscript', max_length=200, verbose_name='manuscript title'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contents_gis',
            field=models.BooleanField(default=False, verbose_name='Does this submission contain GIS data and mapping?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contents_proprietary',
            field=models.BooleanField(default=False, verbose_name='Does this submission contain restricted or proprietary data?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contents_proprietary_sharing',
            field=models.BooleanField(default=False, verbose_name='Are you restricted from sharing this data with Odum for verification only?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='high_performance',
            field=models.BooleanField(default=False, verbose_name='Does this submission require a high-performance compute environment?'),
        ),
    ]
