# Generated by Django 2.2.10 on 2020-02-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200226_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curation',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='manuscript',
            options={'permissions': [('manage_authors_on_manuscript', 'Can manage authors on manuscript'), ('manage_editors_on_manuscript', 'Can manage editors on manuscript'), ('manage_curators_on_manuscript', 'Can manage curators on manuscript'), ('manage_verifiers_on_manuscript', 'Can manage verifiers on manuscript'), ('add_submission_to_manuscript', 'Can add submission to manuscript'), ('add_curation_to_manuscript', 'Can add curation to manuscript'), ('change_curation_on_manuscript', 'Can change curation on manuscript'), ('add_verification_to_manuscript', 'Can add verification to manuscript'), ('change_verification_on_manuscript', 'Can change verification on manuscript')]},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='verification',
            options={'default_permissions': ()},
        ),
    ]
