# Generated by Django 3.1.5 on 2021-01-26 18:32

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201202_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubmission',
            old_name='version',
            new_name='version_id',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='version',
            new_name='version_id',
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='identifier',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='author',
            name='identifier_scheme',
            field=models.CharField(blank=True, choices=[('ORCID', 'ORCID'), ('ISNI', 'ISNI'), ('LCNA', 'LCNA'), ('VIAF', 'VIAF'), ('GND', 'GND'), ('DAI', 'DAI'), ('ResearcherID', 'ResearcherID'), ('ScopusID', 'ScopusID')], max_length=14, null=True, verbose_name='Identifier Scheme'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='position',
            field=models.IntegerField(help_text='Position/order of the author in the list of authors', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='curation',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('incom_materials', 'Incomplete Materials'), ('major_issues', 'Major Issues'), ('minor_issues', 'Minor Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the curator', max_length=15, verbose_name='Curation Status'),
        ),
        migrations.AlterField(
            model_name='curation',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='text',
            field=models.CharField(default='', max_length=200, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('issues', 'Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the editor', max_length=15, verbose_name='Editor Approval'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='historicalcuration',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('incom_materials', 'Incomplete Materials'), ('major_issues', 'Major Issues'), ('minor_issues', 'Minor Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the curator', max_length=15, verbose_name='Curation Status'),
        ),
        migrations.AlterField(
            model_name='historicalcuration',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='historicaledition',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('issues', 'Issues'), ('no_issues', 'No Issues')], default='new', help_text='Was the submission approved by the editor', max_length=15, verbose_name='Editor Approval'),
        ),
        migrations.AlterField(
            model_name='historicaledition',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_init', 'Awaiting Initial Submission'), ('awaiting_resub', 'Awaiting Resubmission'), ('reviewing', 'Reviewing Submission'), ('processing', 'Processing Submission'), ('completed', 'Completed')], default='new', help_text='The overall status of the manuscript in the review process', max_length=15, verbose_name='Manuscript Status'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email address of the publication contact that will be stored in Dataverse', max_length=254, null=True, verbose_name='Contact Email Address'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='contact_first_name',
            field=models.CharField(blank=True, help_text='First name of the publication contact that will be stored in Dataverse', max_length=150, verbose_name='Contact First Name'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='contact_last_name',
            field=models.CharField(blank=True, help_text='Last name of the publication contact that will be stored in Dataverse', max_length=150, verbose_name='Contact last Name'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Additional info about the manuscript', max_length=1024, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='producer_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Producer First Name'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='producer_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Producer Last Name'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='qual_analysis',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this manuscript needs qualitative analysis', null=True, verbose_name='Qualitative Analysis'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='subject',
            field=models.CharField(blank=True, choices=[('agricultural', 'Agricultural Sciences'), ('arts', 'Arts and Humanities'), ('astronomy', 'Astronomy and Astrophysics'), ('business', 'Business and Management'), ('chemistry', 'Chemistry'), ('computer', 'Computer and Information Science'), ('environmental', 'Earth and Environmental Sciences'), ('engineering', 'Engineering'), ('law', 'Law'), ('mathematics', 'Mathematical Sciences'), ('health', 'Medicine, Health and Life Sciences'), ('physics', 'Physics'), ('social', 'Social Sciences'), ('other', 'Other')], max_length=14, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='title',
            field=models.CharField(default='', help_text='Title of the manuscript', max_length=200, verbose_name='Manuscript Title'),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Note Text'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress_edition', 'In Progress Edition'), ('in_progress_curation', 'In Progress Curation'), ('in_progress_verification', 'In Progress Verification'), ('reviewed_awaiting_report', 'Reviewed Awaiting Report'), ('reviewed_awaiting_approve', 'Reviewed Report Awaiting Approval'), ('returned', 'Returned')], default='new', help_text='The status of the submission in the review process', max_length=25, verbose_name='Submission review status'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='historicalverification',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('not_attempted', 'Not Attempted'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('success_w_mod', 'Success W Mod'), ('success', 'Success')], default='new', help_text='Was the submission able to be verified', max_length=15, verbose_name='Verification Status'),
        ),
        migrations.AlterField(
            model_name='historicalverification',
            name='code_executability',
            field=models.CharField(default='', max_length=2000, verbose_name='Code Executability'),
        ),
        migrations.AlterField(
            model_name='historicalverification',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='text',
            field=models.CharField(default='', max_length=200, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_init', 'Awaiting Initial Submission'), ('awaiting_resub', 'Awaiting Resubmission'), ('reviewing', 'Reviewing Submission'), ('processing', 'Processing Submission'), ('completed', 'Completed')], default='new', help_text='The overall status of the manuscript in the review process', max_length=15, verbose_name='Manuscript Status'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email address of the publication contact that will be stored in Dataverse', max_length=254, null=True, verbose_name='Contact Email Address'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='contact_first_name',
            field=models.CharField(blank=True, help_text='First name of the publication contact that will be stored in Dataverse', max_length=150, verbose_name='Contact First Name'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='contact_last_name',
            field=models.CharField(blank=True, help_text='Last name of the publication contact that will be stored in Dataverse', max_length=150, verbose_name='Contact last Name'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Additional info about the manuscript', max_length=1024, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='producer_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Producer First Name'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='producer_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Producer Last Name'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='qual_analysis',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this manuscript needs qualitative analysis', null=True, verbose_name='Qualitative Analysis'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='subject',
            field=models.CharField(blank=True, choices=[('agricultural', 'Agricultural Sciences'), ('arts', 'Arts and Humanities'), ('astronomy', 'Astronomy and Astrophysics'), ('business', 'Business and Management'), ('chemistry', 'Chemistry'), ('computer', 'Computer and Information Science'), ('environmental', 'Earth and Environmental Sciences'), ('engineering', 'Engineering'), ('law', 'Law'), ('mathematics', 'Mathematical Sciences'), ('health', 'Medicine, Health and Life Sciences'), ('physics', 'Physics'), ('social', 'Social Sciences'), ('other', 'Other')], max_length=14, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.CharField(default='', help_text='Title of the manuscript', max_length=200, verbose_name='Manuscript Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Note Text'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress_edition', 'In Progress Edition'), ('in_progress_curation', 'In Progress Curation'), ('in_progress_verification', 'In Progress Verification'), ('reviewed_awaiting_report', 'Reviewed Awaiting Report'), ('reviewed_awaiting_approve', 'Reviewed Report Awaiting Approval'), ('returned', 'Returned')], default='new', help_text='The status of the submission in the review process', max_length=25, verbose_name='Submission review status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('not_attempted', 'Not Attempted'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('success_w_mod', 'Success W Mod'), ('success', 'Success')], default='new', help_text='Was the submission able to be verified', max_length=15, verbose_name='Verification Status'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='code_executability',
            field=models.CharField(default='', max_length=2000, verbose_name='Code Executability'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='host_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Hosting Institution URL'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='machine_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Machine Type'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='memory_reqs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Memory Reqirements'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='operating_system',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='processor_reqs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Processor Requirements'),
        ),
        migrations.AlterField(
            model_name='verificationmetadata',
            name='scheduler',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Scheduler Module'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='exception_reason',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Exception Reason'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='exceptions',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Exceptions'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='verified_results',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Verified Results'),
        ),
        migrations.AlterField(
            model_name='verificationmetadataaudit',
            name='version',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='badge_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='definition_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Definition URL'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='issuing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issuing Date'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='issuing_org',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Issuing Organization'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='logo_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatabadge',
            name='version',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='source_author_website',
            field=models.BooleanField(blank=True, default=False, verbose_name='Source - Author Website'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='source_cran',
            field=models.BooleanField(blank=True, default=False, verbose_name='Source - CRAN'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='source_dataverse',
            field=models.BooleanField(blank=True, default=False, verbose_name='Source - Dataverse Archive'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='source_default_repo',
            field=models.BooleanField(blank=True, default=False, verbose_name='Source - Default Repository'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='source_other',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Source - Other'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatapackage',
            name='version',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatasoftware',
            name='code_repo_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Code Repository URL'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatasoftware',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='verificationmetadatasoftware',
            name='version',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Version'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('manuscript', 'version_id')},
        ),
    ]
