# Generated by Django 3.2.12 on 2022-03-30 16:48

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_manuscript_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataverseInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('api_token', models.CharField(max_length=200, verbose_name='API Token')),
            ],
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='dataverse_dataset_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='The URL of the dataset after publish to Dataverse.'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='dataverse_parent',
            field=models.TextField(blank=True, default='', help_text='The parent Dataverse targeted for the dataset created with the manuscript info.', max_length=1024, null=True, verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='dataverse_dataset_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='The URL of the dataset after publish to Dataverse.'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='dataverse_parent',
            field=models.TextField(blank=True, default='', help_text='The parent Dataverse targeted for the dataset created with the manuscript info.', max_length=1024, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('completed', 'Completed'), ('published', 'Completed And Published')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('completed', 'Completed'), ('published', 'Completed And Published')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='dataverse_installation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.dataverseinstallation'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='dataverse_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataverseinstallation_manuscripts', to='main.dataverseinstallation'),
        ),
    ]
