# Generated by Django 3.1.7 on 2021-03-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210318_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerinfo',
            name='image_token',
        ),
        migrations.AlterField(
            model_name='containerinfo',
            name='container_port',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
