# Generated by Django 2.2.10 on 2020-02-27 21:59

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200227_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='environment_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
