# Generated by Django 3.1.7 on 2021-03-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210319_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerinfo',
            old_name='container_id',
            new_name='repo_container_id',
        ),
        migrations.RenameField(
            model_name='containerinfo',
            old_name='container_ip',
            new_name='repo_container_ip',
        ),
        migrations.RenameField(
            model_name='containerinfo',
            old_name='container_port',
            new_name='repo_container_port',
        ),
        migrations.RenameField(
            model_name='containerinfo',
            old_name='image_name',
            new_name='repo_image_name',
        ),
        migrations.AddField(
            model_name='containerinfo',
            name='proxy_container_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='containerinfo',
            name='proxy_container_ip',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='containerinfo',
            name='proxy_container_port',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
