# Generated by Django 3.2.5 on 2021-07-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210729_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='curation',
            name='needs_verification',
            field=models.BooleanField(default=True, verbose_name='Needs Verification'),
        ),
        migrations.AddField(
            model_name='historicalcuration',
            name='needs_verification',
            field=models.BooleanField(default=True, verbose_name='Needs Verification'),
        ),
    ]
