# Generated by Django 3.1.5 on 2021-01-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210126_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanuscript',
            name='dataverse_doi',
            field=models.CharField(blank=True, help_text='DOI of the publication in Dataverse', max_length=150, verbose_name='Dataverse DOI'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='dataverse_doi',
            field=models.CharField(blank=True, help_text='DOI of the publication in Dataverse', max_length=150, verbose_name='Dataverse DOI'),
        ),
    ]
