# Generated by Django 3.2.12 on 2022-03-31 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220330_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='dataverse_installation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.dataverseinstallation', verbose_name='Dataverse Installation'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='dataverse_parent',
            field=models.CharField(blank=True, default='', help_text='The parent Dataverse in the installation targeted for the dataset created with the manuscript info.', max_length=1024, null=True, verbose_name='Parent Dataverse'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='dataverse_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataverseinstallation_manuscripts', to='main.dataverseinstallation', verbose_name='Dataverse Installation'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='dataverse_parent',
            field=models.CharField(blank=True, default='', help_text='The parent Dataverse in the installation targeted for the dataset created with the manuscript info.', max_length=1024, null=True, verbose_name='Parent Dataverse'),
        ),
    ]
