# Generated by Django 3.2.5 on 2021-07-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210730_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='needs_verification',
            field=models.BooleanField(default=False, verbose_name='Needs Verification'),
        ),
        migrations.AlterField(
            model_name='historicalcuration',
            name='needs_verification',
            field=models.BooleanField(default=False, verbose_name='Needs Verification'),
        ),
    ]
