# Generated by Django 3.2.12 on 2022-04-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220405_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmanuscript',
            name='dataverse_dataset_url',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='dataverse_dataset_url',
        ),
    ]
