# Generated by Django 3.1.6 on 2021-02-10 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210208_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmanuscript',
            name='gitlab_manuscript_id',
        ),
        migrations.RemoveField(
            model_name='historicalmanuscript',
            name='gitlab_manuscript_path',
        ),
        migrations.RemoveField(
            model_name='historicalmanuscript',
            name='gitlab_submissions_id',
        ),
        migrations.RemoveField(
            model_name='historicalmanuscript',
            name='gitlab_submissions_path',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='gitlab_id',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='gitlab_manuscript_id',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='gitlab_manuscript_path',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='gitlab_submissions_id',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='gitlab_submissions_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gitlab_id',
        ),
        migrations.CreateModel(
            name='GitFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date model was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date model was last updated', verbose_name='updated at')),
                ('sha1', models.CharField(help_text='Generated cryptographic hash of the file contents. Used to tell if a file has changed between versions.', max_length=40, verbose_name='SHA-1')),
                ('path', models.CharField(blank=True, help_text='The path to the file in the repo', max_length=4096, null=True, verbose_name='file path')),
                ('date', models.DateTimeField(verbose_name='file creation date')),
                ('size', models.IntegerField(help_text='The size of the file in bytes', verbose_name='file size')),
                ('tag', models.CharField(choices=[('code', 'Code'), ('data', 'Data'), ('doc_other', 'Documentation - Other'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook')], max_length=14, verbose_name='file type')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='file description')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_gitfiles', to=settings.AUTH_USER_MODEL, verbose_name='Creator User')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor_gitfiles', to=settings.AUTH_USER_MODEL, verbose_name='Last Updating User')),
                ('parent_manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_manuscript', to='main.manuscript')),
                ('parent_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_submission', to='main.submission')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='parent_file',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.gitfile'),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.gitfile'),
        ),
        migrations.DeleteModel(
            name='GitlabFile',
        ),
        migrations.AddIndex(
            model_name='gitfile',
            index=models.Index(fields=['path', 'parent_submission'], name='main_gitfil_path_0dba9a_idx'),
        ),
    ]
