# Generated by Django 3.2.5 on 2021-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_corereinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanuscript',
            name='additional_info',
            field=models.CharField(blank=True, default='', help_text='Additional info about the manuscript (e.g., approved exemptions, restricted data, etc).', max_length=1024, null=True, verbose_name='Additional Info'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='additional_info',
            field=models.CharField(blank=True, default='', help_text='Additional info about the manuscript (e.g., approved exemptions, restricted data, etc).', max_length=1024, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='contact_first_name',
            field=models.CharField(blank=True, help_text='Given name of the publication contact that will be stored in Dataverse', max_length=150, verbose_name='Contact Given Name'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='contact_last_name',
            field=models.CharField(blank=True, help_text='Surname of the publication contact that will be stored in Dataverse', max_length=150, verbose_name='Contact Surname'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='description',
            field=models.CharField(blank=True, default='', help_text='The abstract for the manuscript', max_length=1024, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='pub_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The internal ID from the publication', max_length=200, null=True, verbose_name='Manuscript #'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='qual_analysis',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this manuscript includes qualitative analysis', null=True, verbose_name='Qualitative Analysis'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='contact_first_name',
            field=models.CharField(blank=True, help_text='Given name of the publication contact that will be stored in Dataverse', max_length=150, verbose_name='Contact Given Name'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='contact_last_name',
            field=models.CharField(blank=True, help_text='Surname of the publication contact that will be stored in Dataverse', max_length=150, verbose_name='Contact Surname'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='description',
            field=models.CharField(blank=True, default='', help_text='The abstract for the manuscript', max_length=1024, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='pub_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The internal ID from the publication', max_length=200, null=True, verbose_name='Manuscript #'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='qual_analysis',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this manuscript includes qualitative analysis', null=True, verbose_name='Qualitative Analysis'),
        ),
    ]
