# Generated by Django 3.1.6 on 2021-02-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210210_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitfile',
            name='name',
            field=models.CharField(default='', help_text='The name of the file', max_length=4096, verbose_name='file name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gitfile',
            name='path',
            field=models.CharField(default='', help_text='The path to the file in the repo', max_length=4096, verbose_name='file path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gitfile',
            name='tag',
            field=models.CharField(choices=[('code', 'Code'), ('data', 'Data'), ('doc_other', 'Documentation - Other'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook')], default='-', max_length=14, verbose_name='file type'),
        ),
    ]
