# Generated by Django 3.1.8 on 2021-04-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_containerinfo_network_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerinfo',
            name='repo_container_port',
        ),
        migrations.AddField(
            model_name='containerinfo',
            name='proxy_image_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
