# Generated by Django 3.1.8 on 2021-04-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210409_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerinfo',
            name='proxy_image_name',
        ),
    ]
