# Generated by Django 2.2.10 on 2020-03-19 16:08

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200305_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curation',
            old_name='status',
            new_name='_status',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='status',
            new_name='_status',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='status',
            new_name='_status',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='submission',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('in_progress_curation', 'In Progress - Curation'), ('in_progress_verification', 'In Progress - Verification'), ('reviewed', 'Reviewed')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent_curation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.Curation'),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.File'),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.Submission'),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.Verification'),
        ),
    ]
