# Generated by Django 3.1.8 on 2021-04-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_containerinfo_proxy_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerinfo',
            name='proxy_image_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
