# Generated by Django 2.2.10 on 2020-04-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200319_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='gitlab_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gitlab_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
