# Generated by Django 3.1.6 on 2021-02-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210210_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitfile',
            name='tag',
            field=models.CharField(choices=[('-', '-'), ('code', 'Code'), ('data', 'Data'), ('doc_other', 'Documentation - Other'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook')], default='-', max_length=14, verbose_name='file type'),
        ),
    ]
