# Generated by Django 3.2.12 on 2022-04-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220412_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='editor_submit_date',
            field=models.DateField(blank=True, help_text='The date when editors submitted the submission. Only used when editor use of CORE2 for a manuscript is disabled.', null=True, verbose_name='Editor Submit Date'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='editor_submit_date',
            field=models.DateField(blank=True, help_text='The date when editors submitted the submission. Only used when editor use of CORE2 for a manuscript is disabled.', null=True, verbose_name='Editor Submit Date'),
        ),
    ]
