# Generated by Django 2.2.10 on 2020-05-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200428_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscript',
            old_name='gitlab_id',
            new_name='gitlab_manuscript_id',
        ),
    ]
