# Generated by Django 3.2.13 on 2022-04-15 19:11

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220412_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmanuscript',
            old_name='dataverse_doi',
            new_name='dataverse_fetched_doi',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='dataverse_doi',
            new_name='dataverse_fetched_doi',
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='dataverse_fetched_article_citation',
            field=models.TextField(default='', help_text='The article citation pulled from the dataset connected to this manuscript (via DOI)', verbose_name='Dataverse Article Citation'),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='dataverse_fetched_data_citation',
            field=models.TextField(default='', help_text='The data citation pulled from the dataset connected to this manuscript (via DOI)', verbose_name='Dataverse Data Citation'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='dataverse_fetched_article_citation',
            field=models.TextField(default='', help_text='The article citation pulled from the dataset connected to this manuscript (via DOI)', verbose_name='Dataverse Article Citation'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='dataverse_fetched_data_citation',
            field=models.TextField(default='', help_text='The data citation pulled from the dataset connected to this manuscript (via DOI)', verbose_name='Dataverse Data Citation'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('completed', 'Completed'), ('completed_reported', 'Completed And Reported')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('completed', 'Completed'), ('completed_reported', 'Completed And Reported')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
    ]
