# Generated by Django 3.1.6 on 2021-02-15 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210210_2351'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gitfile',
            name='main_gitfil_path_0dba9a_idx',
        ),
        migrations.AlterField(
            model_name='gitfile',
            name='parent_manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_files', to='main.manuscript'),
        ),
        migrations.AlterField(
            model_name='gitfile',
            name='parent_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='main.submission'),
        ),
        migrations.AlterField(
            model_name='gitfile',
            name='tag',
            field=models.CharField(choices=[('-', '-'), ('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other')], default='-', max_length=14, verbose_name='file type'),
        ),
        migrations.AddIndex(
            model_name='gitfile',
            index=models.Index(fields=['path', 'name', 'parent_submission'], name='main_gitfil_path_3f8907_idx'),
        ),
    ]
