# Generated by Django 3.2.5 on 2021-08-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210811_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmanuscript',
            old_name='title',
            new_name='pub_name',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='title',
            new_name='pub_name',
        ),
    ]
