# Generated by Django 2.2.10 on 2020-06-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_manuscript_gitlab_submissions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='gitlab_manuscript_path',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='gitlab_submissions_path',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
