# Generated by Django 3.1.6 on 2021-02-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210215_2026'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gitfile',
            constraint=models.UniqueConstraint(fields=('path', 'name', 'parent_submission'), name='GitFile submission and path'),
        ),
    ]
