# Generated by Django 2.2.10 on 2020-06-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200602_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='gitlab_manuscript_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='gitlab_submissions_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.TextField(default='', max_length=200),
        ),
    ]
