# Generated by Django 3.2.5 on 2021-08-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210824_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitfile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='file description'),
        ),
        migrations.AlterField(
            model_name='gitfile',
            name='tag',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('data', 'Data'), ('doc_readme', 'Documentation - Readme'), ('doc_codebook', 'Documentation - Codebook'), ('doc_other', 'Documentation - Other')], max_length=14, null=True, verbose_name='file type'),
        ),
    ]
