# Generated by Django 3.1.6 on 2021-02-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210215_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmanuscript',
            name='slug',
        ),
    ]
