# Generated by Django 3.2.13 on 2022-05-17 21:51

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220512_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('pending_dataverse_publish', 'Pending Dataverse Publish'), ('published_to_dataverse', 'Published To Dataverse, '), ('completed_report_sent', 'Completed Report Sent')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('pending_dataverse_publish', 'Pending Dataverse Publish'), ('published_to_dataverse', 'Published To Dataverse, '), ('completed_report_sent', 'Completed Report Sent')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
    ]
