# Generated by Django 3.2.13 on 2022-05-18 19:08

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20220517_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmanuscript',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='additional_info',
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('pending_dataverse_publish', 'Pending Dataverse Publish'), ('published_to_dataverse', 'Published To Dataverse'), ('completed_report_sent', 'Completed Report Sent')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The abstract for the manuscript', null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('awaiting_initial', 'Awaiting Initial Submission'), ('awaiting_resubmission', 'Awaiting Author Resubmission'), ('reviewing', 'Editor Reviewing'), ('processing', 'Processing Submission'), ('pending_dataverse_publish', 'Pending Dataverse Publish'), ('published_to_dataverse', 'Published To Dataverse'), ('completed_report_sent', 'Completed Report Sent')], default='new', help_text='The overall status of the manuscript in the review process', max_length=32, verbose_name='Manuscript Status'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The abstract for the manuscript', null=True, verbose_name='Abstract'),
        ),
    ]
