# Generated by Django 2.2.13 on 2020-07-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200710_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcuration',
            name='changes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='changes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmanuscript',
            name='changes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='changes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='changes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='changes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalverification',
            name='changes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historicalcuration',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalverification',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
