# Generated by Django 2.2.13 on 2020-07-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200710_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalcuration',
            old_name='changes',
            new_name='history_changes_list',
        ),
        migrations.RenameField(
            model_name='historicalfile',
            old_name='changes',
            new_name='history_changes_list',
        ),
        migrations.RenameField(
            model_name='historicalmanuscript',
            old_name='changes',
            new_name='history_changes_list',
        ),
        migrations.RenameField(
            model_name='historicalnote',
            old_name='changes',
            new_name='history_changes_list',
        ),
        migrations.RenameField(
            model_name='historicalsubmission',
            old_name='changes',
            new_name='history_changes_list',
        ),
        migrations.RenameField(
            model_name='historicaluser',
            old_name='changes',
            new_name='history_changes_list',
        ),
        migrations.RenameField(
            model_name='historicalverification',
            old_name='changes',
            new_name='history_changes_list',
        ),
    ]
