# Generated by Django 3.2.5 on 2021-10-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20211004_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaleImageChoices',
            fields=[
                ('wt_id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Image ID in Whole Tale')),
                ('name', models.CharField(max_length=200, verbose_name='Image Name in Whole Tale')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='wt_compute_env',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Whole Tale Compute Environment Format'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='wt_compute_env',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Whole Tale Compute Environment Format'),
        ),
    ]
