# Generated by Django 2.2.13 on 2020-07-10 16:37

from django.db import migrations
import os

class Migration(migrations.Migration):

    #When we upgrade to Django 3.0, we can remove this and use noinput admin command
    #https://docs.djangoproject.com/en/3.0/ref/django-admin/#createsuperuser
    def generate_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        DJANGO_SU_NAME = os.environ.get('DJANGO_SUPERUSER_USERNAME')
        DJANGO_SU_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL')
        DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD)

        #TODO: Pass in gitlab id here?

        superuser.save()

    dependencies = [
        ('main', '0026_auto_20200710_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalcuration',
            old_name='history_changes_list',
            new_name='history_change_list',
        ),
        migrations.RenameField(
            model_name='historicalfile',
            old_name='history_changes_list',
            new_name='history_change_list',
        ),
        migrations.RenameField(
            model_name='historicalmanuscript',
            old_name='history_changes_list',
            new_name='history_change_list',
        ),
        migrations.RenameField(
            model_name='historicalnote',
            old_name='history_changes_list',
            new_name='history_change_list',
        ),
        migrations.RenameField(
            model_name='historicalsubmission',
            old_name='history_changes_list',
            new_name='history_change_list',
        ),
        migrations.RenameField(
            model_name='historicaluser',
            old_name='history_changes_list',
            new_name='history_change_list',
        ),
        migrations.RenameField(
            model_name='historicalverification',
            old_name='history_changes_list',
            new_name='history_change_list',
        ),
        migrations.RunPython(generate_superuser),
    ]
