# Generated by Django 3.2.5 on 2021-10-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20211004_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaleImageChoices',
            new_name='TaleImageChoice',
        ),
        migrations.AlterField(
            model_name='historicalmanuscript',
            name='wt_compute_env',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Whole Tale Compute Environment Format'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='wt_compute_env',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Whole Tale Compute Environment Format'),
        ),
    ]
