# Generated by Django 3.2.5 on 2021-11-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20211004_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tale_id', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Tale ID in Whole Tale')),
                ('manuscript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_tale', to='main.manuscript')),
            ],
        ),
        migrations.CreateModel(
            name='TaleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Instance ID for container in Whole Tale')),
                ('container_url', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Container URL')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_taleversion', to='main.submission')),
            ],
        ),
        migrations.RenameField(
            model_name='taleimagechoice',
            old_name='wt_id',
            new_name='choice_id',
        ),
        migrations.DeleteModel(
            name='TaleInfo',
        ),
    ]
