# Generated by Django 3.2.5 on 2021-11-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20211111_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tale',
            name='manuscript',
        ),
        migrations.DeleteModel(
            name='TaleImageChoice',
        ),
        migrations.RemoveField(
            model_name='taleversion',
            name='submission',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='wt_id',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='User ID in Whole Tale'),
        ),
        migrations.AddField(
            model_name='user',
            name='wt_id',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='User ID in Whole Tale'),
        ),
        migrations.DeleteModel(
            name='Tale',
        ),
        migrations.DeleteModel(
            name='TaleVersion',
        ),
    ]
