# Generated by Django 3.2.5 on 2021-12-02 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_auto_20211130_0115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admins', models.BooleanField(default=False)),
                ('group_id', models.CharField(max_length=24, unique=True, verbose_name='Group ID in Whole Tale')),
                ('corere_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholetale_group', to='auth.group')),
                ('manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_wtgroups', to='main.manuscript')),
            ],
        ),
        migrations.CreateModel(
            name='ImageChoice',
            fields=[
                ('choice_id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Image ID in Whole Tale')),
                ('name', models.CharField(max_length=200, verbose_name='Image Name in Whole Tale')),
            ],
        ),
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tale_id', models.CharField(max_length=24, unique=True, verbose_name='Tale ID in Whole Tale')),
                ('group_connector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupconnector_tale', to='wholetale.groupconnector')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_tales', to='main.manuscript')),
                ('original_tale', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tale_copies', to='wholetale.tale')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_tales', to='main.submission', verbose_name='The submission whose files are in the tale')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=200, verbose_name='Instance ID for container in Whole Tale')),
                ('container_url', models.URLField(max_length=500, verbose_name='Container URL')),
                ('corere_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to=settings.AUTH_USER_MODEL)),
                ('tale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tale_instances', to='wholetale.tale')),
            ],
            options={
                'unique_together': {('tale', 'corere_user')},
            },
        ),
    ]
