# Generated by Django 3.2.5 on 2021-11-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0029_auto_20211115_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tale_id', models.CharField(max_length=24, verbose_name='Tale ID in Whole Tale')),
                ('manuscript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_tale', to='main.manuscript')),
            ],
        ),
        migrations.CreateModel(
            name='TaleImageChoice',
            fields=[
                ('choice_id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Image ID in Whole Tale')),
                ('name', models.CharField(max_length=200, verbose_name='Image Name in Whole Tale')),
            ],
        ),
        migrations.CreateModel(
            name='TaleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=200, verbose_name='Instance ID for container in Whole Tale')),
                ('container_url', models.URLField(max_length=500, verbose_name='Container URL')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_taleversion', to='main.submission')),
                ('tale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tale_versions', to='wholetale.tale')),
            ],
        ),
        migrations.CreateModel(
            name='TaleGroup',
            fields=[
                ('wt_group_id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Group ID in Whole Tale')),
                ('corere_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tale_groups', to='auth.group')),
            ],
        ),
    ]
