# Generated by Django 3.2.5 on 2021-11-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wholetale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaleGroup',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='TaleImageChoice',
            new_name='ImageChoice',
        ),
    ]
