# Generated by Django 3.2.5 on 2021-11-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wholetale', '0002_auto_20211115_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='wt_group_id',
            new_name='group_id',
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='wow', max_length=1024, unique=True, verbose_name='Group Name in Whole Tale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_admins',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='corere_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wholetale_group', to='auth.group'),
        ),
    ]
