# Generated by Django 3.2.5 on 2021-12-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211130_0115'),
        ('wholetale', '0002_alter_tale_original_tale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tale',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_tales', to='main.submission', verbose_name='The submission whose files are in the tale'),
        ),
    ]
