# Generated by Django 3.2.11 on 2022-01-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholetale', '0002_auto_20220117_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagechoice',
            old_name='choice_id',
            new_name='wt_id',
        ),
    ]
