# Generated by Django 3.2.5 on 2021-11-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wholetale', '0003_auto_20211116_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='corere_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholetale_group', to='auth.group'),
        ),
    ]
