# Generated by Django 3.2.5 on 2021-12-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholetale', '0003_alter_tale_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='container_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Container URL'),
        ),
    ]
