# Generated by Django 3.2.5 on 2021-12-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholetale', '0004_alter_instance_container_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='container_id',
            new_name='instance_id',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='container_url',
            new_name='instance_url',
        ),
    ]
