# Generated by Django 3.2.5 on 2021-11-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wholetale', '0004_alter_group_corere_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupConnector',
        ),
    ]
