# Generated by Django 3.2.11 on 2022-01-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholetale', '0004_imagechoice_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagechoice',
            options={'ordering': ['show_last', 'name']},
        ),
        migrations.AddField(
            model_name='imagechoice',
            name='show_last',
            field=models.BooleanField(default=False),
        ),
    ]
