# Generated by Django 3.2.5 on 2021-12-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholetale', '0005_auto_20211207_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tale',
            name='group_connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupconnector_tales', to='wholetale.groupconnector'),
        ),
    ]
