# Generated by Django 3.2.5 on 2021-11-30 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_auto_20211129_1652'),
        ('wholetale', '0005_rename_group_groupconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconnector',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tale',
            name='original_tale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tale_copies', to='wholetale.tale'),
        ),
        migrations.AddField(
            model_name='taleversion',
            name='version_id',
            field=models.CharField(default=1, max_length=24, unique=True, verbose_name='Version ID in Whole Tale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupconnector',
            name='group_id',
            field=models.CharField(max_length=24, unique=True, verbose_name='Group ID in Whole Tale'),
        ),
        migrations.AlterField(
            model_name='tale',
            name='tale_id',
            field=models.CharField(max_length=24, unique=True, verbose_name='Tale ID in Whole Tale'),
        ),
        migrations.AlterUniqueTogether(
            name='taleversion',
            unique_together={('tale', 'submission')},
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=200, verbose_name='Instance ID for container in Whole Tale')),
                ('container_url', models.URLField(max_length=500, verbose_name='Container URL')),
                ('corere_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to=settings.AUTH_USER_MODEL)),
                ('tale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tale_instances', to='wholetale.tale')),
                ('tale_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taleversion_instances', to='wholetale.taleversion')),
            ],
        ),
        migrations.RemoveField(
            model_name='taleversion',
            name='container_id',
        ),
        migrations.RemoveField(
            model_name='taleversion',
            name='container_url',
        ),
    ]
