# Generated by Django 3.2.5 on 2022-01-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholetale', '0007_alter_tale_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Token that goes along with the instance url'),
        ),
    ]
